"use strict";

/**
 * Keyword map for fuzzy category matching.
 * Keys are subcategory names (matching defaultCategories.js).
 * Values are arrays of synonyms, brand names, and common expressions in PT-BR.
 * Used by categoryMatcher.js to identify which category a transaction description belongs to.
 */

const CATEGORY_KEYWORDS = {
  // ── Alimentação ────────────────────────────────────────────────────────────
  "Restaurantes": ["restaurante", "almoço", "jantar", "refeição", "comida", "prato", "self service", "buffet", "rodizio", "rodízio", "bistrô", "bistro", "cozinha"],
  "Supermercado": ["supermercado", "mercado", "extra", "carrefour", "pão de açúcar", "atacadão", "assaí", "assai", "sam's", "sams", "makro", "walmart", "dia%", "compras do mês", "feira de semana"],
  "Delivery": ["delivery", "ifood", "rappi", "aiqfome", "james", "pedido", "motoboy", "entrega", "uber eats", "ubereats", "loggi food"],
  "Lanches": ["lanche", "sanduíche", "sanduiche", "burguer", "burger", "combo", "batata frita", "fritas", "mcdonalds", "mc donalds", "mcdonald's", "bk", "burger king", "subway", "giraffas", "bob's", "bobs"],
  "Padaria": ["padaria", "pão", "pao", "café da manhã", "cafe da manha", "croissant", "bolo", "confeitaria", "pastelaria"],
  "Bar / Bebidas": ["bar", "cerveja", "chopp", "chope", "bebida", "drink", "boteco", "pub", "happy hour", "caipirinha", "vinho", "destilado", "whisky", "vodka", "cachaça", "cachaça", "dose"],
  "Feira / Sacolão": ["feira", "sacolão", "hortifruti", "verdura", "legume", "fruta", "feirinha", "mercadão", "quitanda"],
  "Açougue": ["açougue", "acougue", "carne", "frango", "peixe", "churrasco", "costela", "alcatra", "picanha", "boi", "cordeiro"],
  "Cafeteria": ["cafeteria", "café", "cafe", "starbucks", "espresso", "cappuccino", "latte", "coworking café"],
  "Churrascaria": ["churrascaria", "churrasco", "espeto", "espetinho", "rodizio churrasco", "picanha assada"],
  "Sorveteria / Doceria": ["sorveteria", "sorvete", "doceria", "doce", "brigadeiro", "bolo de pote", "acaí", "acai", "smoothie", "crepe", "waffle"],
  "Pizzaria": ["pizzaria", "pizza", "calzone"],
  "Marmita / Quentinha": ["marmita", "quentinha", "marmitex", "marmita fitness", "almoço executivo", "prato feito", "pf"],
  "Food Truck": ["food truck", "foodtruck", "food park", "festival gastronômico"],
  "Sushi / Japonesa": ["sushi", "sashimi", "japonesa", "temaki", "yakisoba", "hot roll", "uramaki", "culinária japonesa"],
  "Lanchonete": ["lanchonete", "pastel", "coxinha", "salgado", "esfiha", "quibe", "tapioca"],
  "Empório / Orgânicos": ["empório", "emporio", "orgânico", "organico", "natural", "integral", "vegano", "vegetariano", "especiarias"],
  "Minimercado": ["minimercado", "mini mercado", "conveniência", "conveniencia", "loja de conveniência", "am pm", "ampm", "tok stok", "lojas cem"],
  "Hamburgeria": ["hamburgeria", "hamburguer", "hamburger", "smash burger", "artesanal burger", "trash burger"],

  // ── Transporte ─────────────────────────────────────────────────────────────
  "Combustível": ["combustível", "combustivel", "gasolina", "etanol", "alcool", "álcool", "diesel", "gnv", "posto", "abastecimento", "tancar", "abasteci"],
  "Uber / 99": ["uber", "99", "99pop", "cabify", "singapto", "indriver", "corrida", "app de transporte"],
  "Transporte Público": ["metrô", "metro", "ônibus", "onibus", "busão", "brt", "trem", "integração", "bilhete único", "bilhete unico", "sptrans", "condução"],
  "Estacionamento": ["estacionamento", "estacionar", "vaga", "garagem", "zona azul", "manobrista"],
  "Manutenção do Veículo": ["manutenção", "manutencao", "revisão", "revisao", "oficina", "mecânico", "mecanico", "borracharia", "pneu", "troca de óleo", "oil change", "amortecedor", "freio"],
  "Táxi": ["táxi", "taxi", "radiotaxi", "taxista", "táxi convencional"],
  "Pedágio": ["pedágio", "pedagio", "sem parar", "veloe", "conectcar", "autopass", "via fácil"],
  "Seguro do Veículo": ["seguro carro", "seguro veículo", "seguro auto", "seguro moto", "porto seguro", "bradesco auto"],
  "Multa de Trânsito": ["multa", "infração", "infracao", "autuação", "detran", "denatran"],
  "IPVA": ["ipva", "licenciamento", "dpvat"],
  "Aluguel de Carro": ["aluguel de carro", "locacar", "localiza", "movida", "unidas", "hertz", "avis"],
  "Moto / Motocicleta": ["moto", "motocicleta", "motoqueiro", "motoboy", "honda cg", "yamaha", "mototaxi"],
  "Bicicleta / Patinete": ["bicicleta", "bike", "ciclismo", "patinete", "scooter", "tembici", "bike itaú", "yellow", "grin"],
  "Lavagem do Carro": ["lavagem", "lava jato", "lavajato", "lavação", "polimento", "higienização do carro"],
  "Revisão / Mecânica": ["revisão", "revisao", "troca de peça", "suspensão", "alinhamento", "balanceamento", "freios"],
  "Passagem Aérea": ["passagem", "aérea", "aerea", "voo", "vôo", "latam", "gol", "azul", "aviação", "embarque", "aeroporto", "milhas"],
  "Frete / Mudança": ["frete", "mudança", "mudanca", "caminhão", "caminhao", "carreto", "carga", "transportadora"],
  "Fretamento / Van": ["fretamento", "van", "micro-ônibus", "frete escolar", "transporte fretado", "transfer"],

  // ── Moradia ────────────────────────────────────────────────────────────────
  "Aluguel": ["aluguel", "alug", "locação", "locacao", "arrendamento", "mensalidade casa", "renda do apartamento"],
  "Condomínio": ["condomínio", "condominio", "taxa condominial", "síndico", "sindico"],
  "Água": ["água", "agua", "sabesp", "caesb", "cagece", "embasa", "saneamento", "conta de água"],
  "Luz": ["luz", "energia", "eletricidade", "enel", "cemig", "copel", "coelba", "celpe", "concessionária energia", "conta de luz"],
  "Gás": ["gás", "gas", "botijão", "botijao", "comigas", "comgas", "naturgy", "gás natural"],
  "Internet": ["internet", "wi-fi", "wifi", "fibra", "claro net", "vivo fibra", "tim live", "sky", "oi fibra", "banda larga"],
  "Manutenção": ["manutenção casa", "reparo", "encanador", "eletricista", "pintura", "pedreiro", "marceneiro", "hidráulico"],
  "IPTU": ["iptu", "imposto predial", "taxa predial"],
  "Seguro Residencial": ["seguro residencial", "seguro casa", "seguro imóvel", "seguro apartamento"],
  "TV por Assinatura": ["tv por assinatura", "tv a cabo", "net tv", "claro tv", "sky tv", "oi tv", "directv", "canais"],
  "Reforma / Obra": ["reforma", "obra", "construção", "construcao", "ampliação", "restauração", "quebrar parede", "azulejo", "piso"],
  "Limpeza / Faxina": ["faxina", "limpeza", "diarista", "empregada", "doméstica", "domestica", "produto de limpeza"],
  "Eletrodomésticos": ["geladeira", "fogão", "fogao", "micro-ondas", "microondas", "máquina de lavar", "lava-louça", "lavadora", "secadora", "eletrodoméstico"],
  "Móveis e Utensílios": ["móveis", "moveis", "utensílios", "utensilios", "cama", "sofá", "sofa", "mesa", "cadeira", "armário", "armario", "prateleira"],
  "Jardinagem": ["jardim", "plantas", "vasos", "grama", "podagem", "jardineiro", "fertilizante"],
  "Dedetização": ["dedetização", "dedetizacao", "dedetizadora", "fumigação", "exterminar", "barata", "rato", "cupim"],
  "Portaria / Segurança": ["portaria", "segurança", "vigilância", "vigilancia", "câmera", "alarm", "monitoramento"],
  "Decoração": ["decoração", "decoracao", "quadro", "tapete", "cortina", "iluminação", "iluminacao", "lustre", "lâmpada"],
  "Taxa Extra de Condomínio": ["taxa extra", "fundo de reserva", "rateio", "obra condomínio"],
  "Climatização / Ar-condicionado": ["ar condicionado", "ar-condicionado", "climatizador", "ventilador", "aquecedor", "split", "instalação ac"],

  // ── Saúde ─────────────────────────────────────────────────────────────────
  "Consultas": ["consulta", "médico", "medico", "clínica", "clinica", "especialista", "check-up", "checkup"],
  "Medicamentos": ["remédio", "remedio", "medicamento", "comprimido", "antibiótico", "antibiotic", "xarope", "pomada", "injeção", "injecao"],
  "Plano de Saúde": ["plano de saúde", "plano saude", "unimed", "amil", "sulamerica", "bradesco saude", "hapvida", "notredame", "prevent senior", "intermédica"],
  "Academia": ["academia", "smart fit", "smartfit", "bluefit", "bodytech", "musculação", "musculacao", "crossfit", "gym", "fitness"],
  "Farmácia": ["farmácia", "farmacia", "drogaria", "droga raia", "drogaraia", "ultrafarma", "ultrafarmas", "panvel", "nissei", "onofre", "drogasil"],
  "Dentista": ["dentista", "odontológico", "odontologico", "ortodontia", "canal", "restauração dentária", "implante dental"],
  "Psicólogo / Terapia": ["psicólogo", "psicologo", "psicóloga", "psiquiatra", "terapeuta", "terapia", "sessão", "sessao", "análise", "analise", "saúde mental"],
  "Exames e Laboratório": ["exame", "laboratorio", "laboratório", "dasa", "fleury", "hermes pardini", "análise clínica", "hemograma", "ultrassom", "tomografia", "ressonância"],
  "Fisioterapia": ["fisioterapia", "fisioterapeuta", "reabilitação", "reabilitacao", "rpg", "pilates clínico"],
  "Suplementos": ["suplemento", "whey", "creatina", "proteína", "proteina", "bcaa", "pré-treino", "pre-treino", "vitamina"],
  "Nutricionista": ["nutricionista", "nutrição", "nutricao", "dieta", "plano alimentar"],
  "Oftalmologista": ["oftalmologista", "oftalmologia", "olho", "óculos", "oculos", "lente", "consulta olhos"],
  "Hospital / Pronto-Socorro": ["hospital", "pronto-socorro", "pronto socorro", "ubs", "upa", "internação", "internacao", "emergência", "emergencia"],
  "Vacinação": ["vacina", "vacinação", "vacinacao", "imunização", "imunizacao", "imunobiologico"],
  "Acupuntura": ["acupuntura", "acupunturista", "medicina tradicional chinesa", "auriculoterapia"],
  "Pilates / Yoga": ["pilates", "yoga", "stretching", "alongamento", "meditação", "meditacao", "mindfulness"],
  "Óculos / Lentes de Contato": ["óculos", "oculos", "lentes de contato", "armação", "armacao", "óticas", "oticas", "grau", "lente"],
  "Cirurgia": ["cirurgia", "operação", "operacao", "procedimento cirúrgico", "hospital dia"],
  "Plano Odontológico": ["plano odontológico", "plano odontologico", "odonto", "dental"],
  "Ortopedia": ["ortopedia", "ortopedista", "osso", "fratura", "imobilização", "fisio ortopédica"],

  // ── Educação ──────────────────────────────────────────────────────────────
  "Mensalidade": ["mensalidade", "escola", "colégio", "colegio", "ensino", "matrícula", "matricula", "boleto escola"],
  "Cursos": ["curso", "aula", "treinamento", "capacitação", "capacitacao", "workshop"],
  "Livros": ["livro", "livraria", "amazon livros", "saraiva", "cultura livros", "estante virtual", "sebrae livros"],
  "Material Escolar": ["material escolar", "caderno", "caneta", "lápis", "mochila", "estojo", "régua"],
  "Idiomas": ["idioma", "inglês", "ingles", "espanhol", "francês", "frances", "alemão", "alemao", "japonês", "japones", "curso de língua", "duolingo", "babbel", "ccaa", "wizard", "fisk"],
  "Faculdade / Pós-graduação": ["faculdade", "universidade", "graduação", "graduacao", "pós-graduação", "pos-graduacao", "mba", "mestrado", "doutorado", "usp", "unicamp", "unip", "anhanguera", "kroton"],
  "Aplicativos Educacionais": ["duolingo", "coursera", "udemy", "alura", "hotmart", "braip", "eduzz", "khanacademy", "skill share", "skillshare"],
  "Coaching / Mentoria": ["coach", "coaching", "mentoria", "mentor", "consultoria pessoal", "desenvolvimento pessoal"],
  "EAD / Plataformas Online": ["ead", "ensino a distância", "ensino online", "plataforma de ensino", "curso online", "aula online"],
  "Workshops / Conferências": ["workshop", "conferência", "conferencia", "seminário", "seminario", "congresso", "palestra", "evento educacional"],
  "Certificações / Concursos": ["certificação", "certificacao", "concurso", "prova", "exame de certificação", "aws", "gcp", "azure", "pmp", "enem"],
  "Escola de Música / Arte": ["música", "musica", "violão", "violao", "guitarra", "piano", "canto", "desenho", "pintura", "dança", "danca", "balé", "bale"],
  "Reforço Escolar": ["reforço", "refoco", "professor particular", "aula particular", "tutoria"],
  "Intercâmbio": ["intercâmbio", "intercambio", "estudo no exterior", "estudo fora", "visto estudante", "curso no exterior"],
  "Treinamentos Corporativos": ["treinamento corporativo", "in company", "liderança", "gestão", "gestao"],
  "Papelaria": ["papelaria", "caneta", "papel", "bloco", "caderno", "agenda", "post-it"],
  "Assinatura Educacional": ["assinatura educacional", "plataforma educação", "plano educação", "acesso a cursos"],

  // ── Lazer ─────────────────────────────────────────────────────────────────
  "Cinema": ["cinema", "cinemark", "cinesystem", "kinoplex", "ingresso", "popcorn", "pipoca", "filme"],
  "Viagens": ["viagem", "hotel", "pousada", "airbnb", "booking", "hospedagem", "passagem", "turismo", "resort", "excursão"],
  "Jogos": ["jogo", "game", "steam", "playstation", "xbox", "nintendo", "psn", "dlc", "in-game", "loot box"],
  "Streaming": ["netflix", "hbo", "max", "disney", "disney plus", "amazon prime", "star plus", "globoplay", "paramount", "crunchyroll", "apple tv", "streaming"],
  "Shows / Eventos": ["show", "evento", "festival", "ingresso", "rock in rio", "lollapalooza", "balada", "festa", "rave"],
  "Esportes": ["futebol", "tênis", "quadra", "campo", "aluguel campo", "mensalidade clube", "natação", "natacao", "vôlei", "volei", "basquete"],
  "Hobbies": ["hobby", "coleção", "colecao", "miniaturas", "fotografia", "camera", "drone", "pesca", "jardinagem hobby", "artesanato"],
  "Parques / Passeios": ["parque", "passeio", "zoo", "zoológico", "zoologico", "jardim botânico", "botanico", "atração", "atracao"],
  "Teatro / Dança": ["teatro", "dança", "danca", "espetáculo", "espetaculo", "ballet", "ópera", "opera", "musicais"],
  "Museus / Exposições": ["museu", "exposição", "exposicao", "galeria", "arte", "cultural", "pinacoteca"],
  "Festas / Baladas": ["festa", "balada", "boate", "clube noturno", "bar noturno", "aniversário", "aniversario"],
  "Camping / Natureza": ["camping", "acampamento", "trilha", "ecoturismo", "barraca", "fogueira", "natureza"],
  "Clubes / Associações": ["clube", "associação", "associacao", "sócio", "socio", "mensalidade clube"],
  "Spa / Wellness": ["spa", "massagem", "relaxamento", "wellness", "sauna", "banho turco"],
  "Boliche / Laser Tag": ["boliche", "laser tag", "lasertag", "fliperama", "fliperama", "paintball", "go-kart", "kart"],
  "Karaokê": ["karaokê", "karaoke", "karaokê bar"],
  "Beach Tennis": ["beach tennis", "vôlei de praia", "areia", "kitesurf", "surf", "paddleboard"],
  "Circo / Parques Temáticos": ["circo", "parque temático", "parque tematico", "hopi hari", "beto carrero", "playcenter", "montanha russa"],

  // ── Compras ────────────────────────────────────────────────────────────────
  "Roupas": ["roupa", "vestuário", "vestuario", "camisa", "calça", "calca", "blusa", "vestido", "zara", "c&a", "renner", "riachuelo", "hering", "lojas americanas"],
  "Eletrônicos": ["eletrônico", "eletronico", "celular", "smartphone", "notebook", "computador", "tablet", "fone", "headphone", "alexa", "smart watch", "apple", "samsung", "xiaomi"],
  "Casa e Decoração": ["casa e decoração", "tok stok", "leroy merlin", "casas bahia", "magazine luiza", "decoração casa"],
  "Presentes": ["presente", "mimo", "brinde", "lembrança", "surpresa", "embalagem presente"],
  "Calçados": ["calçado", "calcado", "tênis", "tenis", "sapato", "sandália", "sandalia", "rasteira", "bota", "chinelo", "havaianas"],
  "Acessórios": ["acessório", "acessorio", "cinto", "bolsa", "carteira", "mochila", "mala", "relogio", "relógio"],
  "Beleza e Higiene": ["shampoo", "sabonete", "desodorante", "creme", "loção", "locao", "escova", "pasta de dente", "absorvente", "hidratante", "perfume"],
  "Mercado Online": ["amazon", "mercado livre", "shopee", "aliexpress", "shein", "americanas", "netshoes", "submarino", "kabum"],
  "Ferramentas": ["ferramenta", "parafuso", "furadeira", "chave de fenda", "martelo", "leroy merlin", "telhanorte"],
  "Artigos para Bebê": ["bebê", "bebe", "fralda", "mamadeira", "chupeta", "carrinho de bebê", "berço", "berco", "roupinha de bebê"],
  "Cama / Mesa / Banho": ["lençol", "lencol", "toalha", "travesseiro", "colchão", "colchao", "edredom", "jogo americano"],
  "Brinquedos": ["brinquedo", "boneca", "carrinho", "lego", "quebra-cabeça", "lúdico", "infantil"],
  "Bijuterias / Joias": ["bijuteria", "joia", "anel", "brinco", "colar", "pulseira", "ouro", "prata", "ouro branco"],
  "Instrumentos Musicais": ["violão", "violao", "guitarra", "bateria", "teclado", "saxofone", "flauta", "instrumento musical"],
  "Artesanato": ["artesanato", "crochê", "croche", "tricô", "trico", "bordado", "pintura em tela", "resina"],
  "Papelaria / Escritório": ["caneta", "papel", "impressora", "toner", "cartucho", "caderno", "bloco", "pasta"],
  "Móveis": ["móvel", "movel", "sofá", "sofa", "cama", "mesa", "cadeira", "guarda-roupa", "armário", "armario", "estante", "rack"],

  // ── Finanças ───────────────────────────────────────────────────────────────
  "Investimentos": ["investimento", "aplicação", "aplicacao", "aportar", "aporte", "fundo", "cdb", "tesouro direto", "lci", "lca", "debenture"],
  "Seguros": ["seguro", "apólice", "apolice", "sinistro", "prêmio seguro", "porto seguro", "sulamerica seguro"],
  "Impostos": ["imposto", "darf", "irpf", "irpj", "ir", "imposto de renda", "receita federal", "tributo", "iss", "icms"],
  "Tarifa Bancária": ["tarifa", "taxa bancária", "taxa bancaria", "ted", "doc", "pix taxa", "manutenção conta", "anuidade cartão"],
  "Empréstimo / Financiamento": ["empréstimo", "emprestimo", "financiamento", "parcela", "prestação", "prestacao", "crédito", "credito", "cdc", "cet"],
  "Previdência Privada": ["previdência", "previdencia", "pgbl", "vgbl", "aposentadoria", "fgts", "funpresp"],
  "Câmbio": ["câmbio", "cambio", "dólar", "dolar", "euro", "libra", "moeda estrangeira", "remessa", "wise", "remessa online"],
  "Criptomoedas": ["cripto", "criptomoeda", "bitcoin", "btc", "ethereum", "eth", "usdt", "binance", "coinbase", "mercado bitcoin", "foxbit"],
  "Ações / Bolsa": ["ação", "acao", "ações", "acoes", "bolsa", "b3", "bovespa", "brokerage", "corretagem", "dividendo", "fii"],
  "Renda Fixa / CDB": ["renda fixa", "cdb", "lci", "lca", "tesouro", "debênture", "debenture", "poupança rendimento"],
  "Consórcio": ["consórcio", "consorcio", "lance", "contemplação", "contemplacao", "parcela consórcio"],
  "IOF / Taxas Bancárias": ["iof", "iof câmbio", "iof empréstimo", "taxa", "spread"],
  "Multa / Juros": ["multa", "juro", "mora", "encargo", "atraso pagamento", "juros atraso"],
  "Corretora / Custódia": ["corretora", "custódia", "custodia", "xp investimentos", "rico", "modalmais", "clear", "inter invest"],
  "Resgate / Saque": ["resgate", "saque", "retirada", "debito conta"],
  "Fundo de Emergência": ["fundo de emergência", "fundo emergencia", "reserva de emergência", "reserva financeira"],
  "Poupança": ["poupança", "poupanca", "caderneta", "cofrinho digital"],

  // ── Receitas ───────────────────────────────────────────────────────────────
  "Salário": ["salário", "salario", "contracheque", "holerite", "pagamento", "remuneração", "remuneracao", "renda mensal", "adiantamento"],
  "Freelance": ["freelance", "freela", "freelas", "trabalho avulso", "job", "trampo", "projeto", "honorários", "honorarios"],
  "Aluguel Recebido": ["aluguel recebido", "renda aluguel", "locação recebida", "inquilino pagou"],
  "Dividendos": ["dividendo", "dividendos", "jcp", "juros sobre capital", "yield", "proventos", "fii dividendo"],
  "Outros Rendimentos": ["rendimento", "renda extra", "ganho", "outros", "renda passiva"],
  "Bônus / 13º": ["bônus", "bonus", "13º", "13 salário", "13 salario", "décimo terceiro", "decimo terceiro", "gratificação", "gratificacao"],
  "Renda Extra": ["renda extra", "bico", "extra", "renda complementar", "trabalho extra"],
  "Venda de Itens": ["venda", "vendi", "vendeu", "mercado livre venda", "shopee venda", "olx", "enjoei", "venda de produto"],
  "Bolsa / Auxílio": ["bolsa", "auxílio", "auxilio", "bolsa família", "benefício", "beneficio", "prouni", "capes", "fies", "auxílio emergencial"],
  "Cashback / Reembolso": ["cashback", "reembolso", "estorno", "devolução", "devolucao", "cash back"],
  "PLR / Participação nos Lucros": ["plr", "participação nos lucros", "participacao nos lucros", "resultado", "gratificação pj"],
  "Pensão / Alimônia": ["pensão", "pensao", "alimônia", "alimonia", "pensão alimentícia", "pensao alimenticia"],
  "Prêmio / Sorteio": ["prêmio", "premio", "sorteio", "loteria", "raspadinha", "mega-sena", "quina", "lotomania"],
  "Comissão de Vendas": ["comissão", "comissao", "comissão de venda", "bonificação", "bonificacao"],
  "Royalties": ["royalties", "royaltie", "direito autoral", "licença", "licenca", "propriedade intelectual"],
  "Vale / Benefício Empresa": ["vale refeição", "vale alimentação", "vale transporte", "vt", "va", "vr", "vale cultura", "benefício empresa"],
  "Herança": ["herança", "heranca", "inventário", "inventario", "partilha", "espólio"],
  "Venda de Criptomoedas": ["venda cripto", "venda bitcoin", "venda btc", "cripto venda", "trade cripto", "lucro cripto"],

  // ── Pets ───────────────────────────────────────────────────────────────────
  "Ração": ["ração", "racao", "comida pet", "petisco", "snack pet", "golden", "pedigree", "royal canin", "whiskas"],
  "Veterinário": ["veterinário", "veterinario", "vet", "clínica veterinária", "clinica veterinaria", "consulta pet"],
  "Pet Shop": ["pet shop", "petshop", "loja pet", "cobasi", "petz"],
  "Banho e Tosa": ["banho", "tosa", "banho e tosa", "grooming", "toalhinha pet"],
  "Remédios": ["remédio pet", "medicamento animal", "antiparasitário", "antipulgas", "vermifugo", "vermífugo"],
  "Vacinas Pet": ["vacina pet", "vacinação pet", "vacina animal", "v10", "antirrábica"],
  "Seguro Pet": ["seguro pet", "seguro animal", "plano pet"],
  "Creche / Hospedagem": ["creche pet", "hotel pet", "hospedagem pet", "day care pet", "pensão pet"],
  "Adestramento": ["adestramento", "treinamento pet", "adestrador", "obediência canina"],
  "Acessórios e Brinquedos": ["acessório pet", "brinquedo pet", "coleira", "guia", "cama pet", "arranhador"],
  "Cirurgia Veterinária": ["cirurgia pet", "cirurgia veterinária", "operação animal"],
  "Plano de Saúde Pet": ["plano pet", "saúde animal", "plano veterinário"],
  "Castração": ["castração", "castracao", "castrar", "esterilização"],

  // ── Beleza e Cuidados Pessoais ─────────────────────────────────────────────
  "Cabeleireiro / Barbearia": ["cabeleireiro", "cabeleireira", "barbearia", "barba", "corte", "tintura", "coloração", "coloracao", "escova", "salão", "salao"],
  "Manicure / Pedicure": ["manicure", "pedicure", "unheiro", "nail", "esmalteria", "studio de unhas", "gel"],
  "Cosméticos": ["cosmético", "cosmetico", "maquiagem", "batom", "base", "blush", "sombra", "primer", "loreal", "maybelline"],
  "Perfumaria": ["perfume", "colônia", "colonia", "eau de parfum", "fragrância", "fragancia", "o boticário", "o boticario"],
  "Depilação": ["depilação", "depilacao", "cera", "laser depilação", "depilação a laser", "epilação"],
  "Skincare": ["skincare", "hidratante", "sérum", "serum", "protetor solar", "filtro solar", "vitamina c pele", "ácido hialurônico", "retinol"],
  "Spa / Massagem": ["spa", "massagem", "relaxamento", "shiatsu", "drenagem", "pedras quentes"],
  "Tatuagem / Piercing": ["tatuagem", "tattoo", "tatuador", "piercing", "body art"],
  "Maquiagem Profissional": ["maquiagem profissional", "make up", "makeup artist", "maquiador", "maquiadora"],
  "Lash Designer": ["lash", "cílios", "cilios", "alongamento de cílios", "volume russo", "sobrancelha", "henna sobrancelha", "design de sobrancelha"],
  "Bronzeamento": ["bronzeamento", "câmara de bronzeamento", "autobronzeador", "bronzer"],
  "Micropigmentação": ["micropigmentação", "micropigmentacao", "tatuagem de sobrancelha", "lábio", "labio"],
  "Procedimentos Estéticos": ["botox", "harmonização", "harmonizacao", "preenchimento", "ácido hialurônico rosto", "estética", "estetica"],

  // ── Assinaturas ────────────────────────────────────────────────────────────
  "Streaming (Vídeo)": ["netflix", "hbo", "max", "disney plus", "disney+", "amazon prime video", "star plus", "globoplay", "paramount plus", "mubi", "apple tv plus"],
  "Streaming (Música)": ["spotify", "apple music", "deezer", "tidal", "amazon music", "youtube music"],
  "Apps e Serviços": ["assinatura app", "plano mensal app", "premium", "subscription", "mensalidade app"],
  "Clube de Assinaturas": ["clube", "box mensal", "assine", "signature box", "tag livros", "leiturinha"],
  "Jornal / Revista Digital": ["jornal", "revista", "uol", "folha", "estadão", "globo", "veja", "época", "piauí"],
  "VPN / Segurança Online": ["vpn", "nordvpn", "expressvpn", "surfshark", "segurança digital", "privacy"],
  "Armazenamento em Nuvem": ["icloud", "google one", "dropbox", "onedrive", "google drive pago", "nuvem"],
  "Game Pass / Gaming": ["game pass", "xbox game pass", "psn plus", "playstation plus", "nintendo online", "ea play"],
  "E-books / Audiobooks": ["kindle unlimited", "audible", "storytel", "bookmate", "e-book", "audiobook"],
  "Software Profissional": ["adobe", "photoshop", "illustrator", "figma", "notion", "canva pro", "microsoft 365", "office 365", "autocad"],
  "Antivírus": ["antivírus", "antivirus", "norton", "kaspersky", "avast", "mcafee", "bitdefender"],
  "Ferramentas SaaS": ["saas", "hubspot", "salesforce", "slack", "zoom", "asana", "trello", "monday", "clickup"],

  // ── Trabalho e Negócios ────────────────────────────────────────────────────
  "Equipamentos": ["equipamento", "notebook trabalho", "monitor", "teclado", "mouse", "câmera profissional", "microfone", "headset"],
  "Software / Licenças": ["licença", "licenca", "software", "sistema", "erp", "crm", "antivírus empresa"],
  "Marketing": ["marketing", "anúncio", "anuncio", "publicidade", "mídia", "midia", "campanha", "impulsionar", "tráfego pago"],
  "Despesas de Escritório": ["escritório", "escritorio", "material escritório", "papel escritório", "toner", "recarga"],
  "Contabilidade / Contador": ["contador", "contabilidade", "escritório contábil", "honorário contábil", "nota fiscal"],
  "Advogado / Jurídico": ["advogado", "jurídico", "juridico", "advocacia", "honorário jurídico", "contrato"],
  "Logística / Frete": ["logística", "logistica", "frete empresarial", "envio", "correios", "sedex", "transportadora"],
  "Embalagens": ["embalagem", "caixa", "envelope", "plástico", "plastico", "fita", "etiqueta"],
  "Folha de Pagamento": ["folha de pagamento", "salário funcionário", "encargo trabalhista", "fgts empresa", "inss empresa"],
  "Impostos Empresariais": ["simples nacional", "das", "inss pj", "iss empresa", "irpj", "csll", "pgbl empresa"],
  "Propaganda / Anúncios": ["google ads", "facebook ads", "meta ads", "instagram ads", "tiktok ads", "impulsionamento"],
  "Freelancers Contratados": ["freelancer contratado", "prestador", "pj contratado", "rpa", "serviço de terceiro"],
  "Viagens Corporativas": ["viagem corporativa", "viagem de negócios", "viagem a trabalho", "diária hotel", "passagem trabalho"],
  "Telefone Empresarial": ["telefone empresa", "celular corporativo", "plano corporativo", "linha pj"],

  // ── Doações e Presentes ────────────────────────────────────────────────────
  "Doações": ["doação", "doacao", "doei", "contribuição", "contribuicao", "ajuda financeira"],
  "Presentes (Aniversário)": ["presente aniversário", "presente aniversario", "festa aniversário", "bolo aniversário"],
  "Presentes (Natal)": ["presente natal", "amigo secreto", "natal", "ceia de natal"],
  "Igreja / Dízimo": ["dízimo", "dizimo", "oferta", "Igreja", "congregação", "congregacao", "contribuição religiosa"],
  "ONG / Caridade": ["ong", "caridade", "instituição", "instituicao", "obra social", "fundação", "fundacao"],
  "Vaquinha Online": ["vaquinha", "vaquinha online", "abacashi", "vakinha", "benfeitoria", "catarse", "crowdfunding"],
  "Floricultura": ["flores", "bouquet", "buquê", "buque", "arranjo floral", "floricultura", "plantas presente"],
  "Amigo Oculto": ["amigo oculto", "amigo secreto", "troca de presentes"],
  "Chá de Bebê / Casamento": ["chá de bebê", "cha de bebe", "casamento presente", "lista de casamento", "chá bar", "cha de lingerie"],
  "Cartão / Lembrança": ["cartão", "cartao", "lembrança", "lembranca", "mimo pequeno", "postais"],
  "Confraternização": ["confraternização", "confraternizacao", "almoço empresa", "jantar empresa", "festinha"],
  "Adoção Simbólica": ["adoção simbólica", "adocao simbolica", "apadrinhar", "padrinho"],
};

/**
 * Flat list of all category/subcategory names for normalization reference.
 * Format: { name, parent, keywords }
 */
function buildCategoryIndex() {
  const index = [];
  for (const [subName, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    index.push({ name: subName, keywords });
  }
  return index;
}

const CATEGORY_INDEX = buildCategoryIndex();

module.exports = { CATEGORY_KEYWORDS, CATEGORY_INDEX };
